# Generated by Django 6.1.2 on 2026-10-08 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0003_question_code_snippet_question_explanation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Turnir nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Turnir haqida')),
                ('start_date', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('end_date', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('duration_minutes', models.PositiveIntegerField(default=15, verbose_name='Ajratilgan vaqt (daqiqa)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('prize_title', models.CharField(default='Haftalik Django Chempioni Kubogi', max_length=120, verbose_name='Mukofot')),
                ('questions', models.ManyToManyField(related_name='tournaments', to='quiz.question', verbose_name='Turnir savollari')),
            ],
            options={
                'verbose_name': 'Turnir',
                'verbose_name_plural': 'Turnirlar',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name="To'plangan ball")),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Jami savollar')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Sarflangan vaqt (soniya)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan vaqt')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='tournament.tournament', verbose_name='Turnir')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Turnir ishtirokchisi',
                'verbose_name_plural': 'Turnir ishtirokchilari',
                'ordering': ['-score', 'time_spent_seconds'],
                'unique_together': {('tournament', 'user')},
            },
        ),
    ]
