# Generated by Django 6.1.2 on 2026-10-08 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Belgi'),
        ),
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Sana')),
                ('bonus_points', models.PositiveIntegerField(default=5, verbose_name='Bonus ball')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges', to='quiz.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Kunlik savol',
                'verbose_name_plural': 'Kunlik savollar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyChallengeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'rimi?")),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='Urinilgan vaqt')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.dailychallenge', verbose_name='Kunlik sinov')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.choice', verbose_name='Tanlangan javob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Kunlik savol urinishi',
                'verbose_name_plural': 'Kunlik savol urinishlari',
                'unique_together': {('user', 'challenge')},
            },
        ),
        migrations.CreateModel(
            name='UserMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Xato qilingan vaqt')),
                ('is_resolved', models.BooleanField(default=False, verbose_name="To'g'rilandimi?")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mistakes', to='quiz.question', verbose_name='Savol')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.choice', verbose_name="Tanlangan noto'g'ri javob")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Xato qilingan savol',
                'verbose_name_plural': 'Xato qilingan savollar',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
