# Generated by Django 6.1.2 on 2026-10-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_category_icon_dailychallenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code_snippet',
            field=models.TextField(blank=True, default='', verbose_name='Kod parchasi'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default='', verbose_name='Tushuntirish / Izoh'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('choice', 'Oddiy variantlar'), ('code_fill', "Koddagi bo'sh joyni to'ldirish")], default='choice', max_length=20, verbose_name='Savol turi'),
        ),
    ]
