# Generated by Django 6.1.2 on 2026-10-07 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name="To'plangan ball")),
                ('total_questions', models.PositiveIntegerField(verbose_name='Jami savollar')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar soni")),
                ('details', models.JSONField(blank=True, default=list, verbose_name='Batafsil javoblar')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Tugatilgan vaqt')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='quiz.category', verbose_name='Kategoriya')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_scores', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi natijasi',
                'verbose_name_plural': 'Foydalanuvchi natijalari',
                'ordering': ['-score', '-completed_at'],
            },
        ),
    ]
