# Generated by Django 6.1.2 on 2026-10-08 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=100, verbose_name='Nishon nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('icon_svg', models.TextField(verbose_name='SVG belgisi')),
                ('points_reward', models.PositiveIntegerField(default=50, verbose_name='Bonus ball')),
                ('category', models.CharField(default='general', max_length=30, verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Nishon',
                'verbose_name_plural': 'Nishonlar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Berilgan vaqt')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_users', to='leaderboard.badge', verbose_name='Nishon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi nishoni',
                'verbose_name_plural': 'Foydalanuvchi nishonlari',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
