# Generated by Django 6.1.2 on 2026-10-08 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0002_alter_category_icon_dailychallenge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=20, unique=True, verbose_name='Xona kodi')),
                ('status', models.CharField(choices=[('waiting', 'Kutilmoqda'), ('active', 'Davom etmoqda'), ('finished', 'Yakunlangan')], default='waiting', max_length=15, verbose_name='Holat')),
                ('creator_score', models.PositiveIntegerField(default=0, verbose_name='Tashkilotchi bali')),
                ('opponent_score', models.PositiveIntegerField(default=0, verbose_name='Raqib bali')),
                ('creator_progress', models.PositiveIntegerField(default=0, verbose_name='Tashkilotchi bosqichi')),
                ('opponent_progress', models.PositiveIntegerField(default=0, verbose_name='Raqib bosqichi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='quiz.category', verbose_name='Kategoriya')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_battles', to=settings.AUTH_USER_MODEL, verbose_name='Tashkilotchi')),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joined_battles', to=settings.AUTH_USER_MODEL, verbose_name='Raqib')),
                ('questions', models.ManyToManyField(related_name='battles', to='quiz.question', verbose_name='Savollar')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_battles', to=settings.AUTH_USER_MODEL, verbose_name="G'olib")),
            ],
            options={
                'verbose_name': '1v1 Bellashuv xonasi',
                'verbose_name_plural': '1v1 Bellashuv xonalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
